{pkgs, ...}: let
  servers = {
    # Frontend
    html = pkgs.vscode-langservers-extracted;
    cssls = pkgs.vscode-langservers-extracted;
    jsonls = pkgs.vscode-langservers-extracted;
    css_variables = pkgs.vscode-langservers-extracted;
    yamlls = pkgs.yaml-language-server;
    marksman = pkgs.marksman;
    ts_ls = pkgs.typescript-language-server;
    emmet_ls = pkgs.emmet-ls;
    astro = pkgs.astro-language-server;
    svelte = pkgs.svelte-language-server;
    prismals = pkgs.prisma-language-server;
    intelephense = pkgs.intelephense;

    # Backend
    jdtls = pkgs.jdt-language-server;
    docker_language_server = pkgs.docker-compose-language-service;
    dockerls = pkgs.dockerfile-language-server;
    lemminx = pkgs.lemminx;
    sqls = pkgs.sqls;
    gopls = pkgs.gopls;

    # General
    qmlls = pkgs.qt6.qtdeclarative;
    taplo = pkgs.taplo;
    lua_ls = pkgs.lua-language-server;
    pyright = pkgs.pyright;
    bashls = pkgs.bash-language-server;
    rust_analyzer = pkgs.rustup;
    hyprls = pkgs.hyprls;
    clangd = pkgs.clang-tools;
    zls = pkgs.zls;
    nixd = pkgs.nixd;
  };
in {
  home.packages = builtins.attrValues servers;

  home.file.".local/share/nvim/nix-servers.lua".text =
    "-- Auto-generated by modules/dev/lsp.nix — do not edit manually\n"
    + "return {\n"
    + builtins.concatStringsSep "\n" (map (name: "  \"${name}\",") (builtins.attrNames servers))
    + "\n}\n";
}
