{ pkgs, lib, ... }:

let
  vsc-langservers = pkgs.vscode-langservers-extracted;

  servers = {
    # Frontend
    html = vsc-langservers;
    cssls = vsc-langservers;
    jsonls = vsc-langservers;
    css_variables = pkgs.css-variables-language-server;
    yamlls = pkgs.yaml-language-server;
    ts_ls = pkgs.typescript-language-server;
    emmet_ls = pkgs.emmet-ls;
    astro = pkgs.astro-language-server;
    svelte = pkgs.svelte-language-server;
    prismals = pkgs.prisma-language-server;

    # Backend
    jdtls = pkgs.jdt-language-server;
    docker_language_server = pkgs.docker-compose-language-service;
    dockerls = pkgs.dockerfile-language-server;

    # General
    qmlls = pkgs.qt6.qtdeclarative;
    lua_ls = pkgs.lua-language-server;
    bashls = pkgs.bash-language-server;
    rust_analyzer = pkgs.rustup;
    clangd = pkgs.clang-tools;

    inherit (pkgs)
      marksman
      intelephense
      lemminx
      sqls
      gopls
      taplo
      pyright
      hyprls
      zls
      nixd
      ;
  };
in
{
  home.packages = builtins.attrValues servers;

  home.file.".local/share/nvim/nix-servers.lua".text =
    let
      entries = map (name: "  \"${name}\",") (builtins.attrNames servers);
    in
    lib.concatStringsSep "\n" (
      [
        "-- Auto-generated by modules/dev/lsp.nix — do not edit manually"
        "return {"
      ]
      ++ entries
      ++ [ "}" ]
    )
    + "\n";
}
