{ pkgs, lib, ... }:

let
  vsc-langservers = pkgs.vscode-langservers-extracted;

  servers = {
    # Frontend
    html = vsc-langservers;
    cssls = vsc-langservers;
    jsonls = vsc-langservers;
    css_variables = vsc-langservers;
    yamlls = pkgs.yaml-language-server;
    inherit (pkgs) marksman;
    ts_ls = pkgs.typescript-language-server;
    emmet_ls = pkgs.emmet-ls;
    astro = pkgs.astro-language-server;
    svelte = pkgs.svelte-language-server;
    prismals = pkgs.prisma-language-server;
    inherit (pkgs) intelephense;

    # Backend
    jdtls = pkgs.jdt-language-server;
    docker_language_server = pkgs.docker-compose-language-service;
    dockerls = pkgs.dockerfile-language-server;
    inherit (pkgs) lemminx;
    inherit (pkgs) sqls;
    inherit (pkgs) gopls;

    # General
    qmlls = pkgs.qt6.qtdeclarative;
    inherit (pkgs) taplo;
    lua_ls = pkgs.lua-language-server;
    inherit (pkgs) pyright;
    bashls = pkgs.bash-language-server;
    rust_analyzer = pkgs.rustup;
    inherit (pkgs) hyprls;
    clangd = pkgs.clang-tools;
    inherit (pkgs) zls;
    inherit (pkgs) nixd;
  };
in
{
  home.packages = builtins.attrValues servers;

  home.file.".local/share/nvim/nix-servers.lua".text =
    lib.concatStringsSep "\n" [
      "-- Auto-generated by modules/dev/lsp.nix — do not edit manually"
      "return {"
      (builtins.concatStringsSep "\n" (map (name: "  \"${name}\",") (builtins.attrNames servers)))
      "}"
    ]
    + "\n";
}
